name: Docker Build

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: false
          load: true
          tags: mk-wedding-rsvp-api:test

      - name: Show image size
        run: |
          docker image ls mk-wedding-rsvp-api:test

      - name: Inspect image size
        run: |
          docker image inspect mk-wedding-rsvp-api:test \
            --format='Image size: {{.Size}} bytes'

      - name: Inspect image layers
        run: |
          docker history mk-wedding-rsvp-api:test